apiVersion: v1
kind: Namespace
metadata:
  name: project-wta
---         
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-wta-aut-redis-dep
  namespace: project-wta
  labels:
    app: project-wta-redis
    role: leader
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-wta-redis
  template:
    metadata:
      labels:
        app: project-wta-redis
        role: leader
        tier: backend
    spec:
      containers:
      - name: redis
        image: "redis:latest"
        resources:
          requests:
            cpu: 80m
            memory: 80Mi
          limits:
            cpu: 160m
            memory: 160Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: project-wta-aut-redis-svc
  namespace: project-wta
  labels:
    app: project-wta-redis
    role: leader
    tier: backend
spec:
  ports:
  - name: project-wta-redis
    protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: project-wta-redis
    role: leader
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: project-wta-aut-api-svc
  namespace: project-wta
spec:
  selector:
    app: project-wta
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: project-wta
    protocol: TCP
    port: 80
    targetPort: 80
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  project-wta-aut-api-dep
  namespace: project-wta
  labels:
    app:  project-wta
spec:
  selector:
    matchLabels:
      app: project-wta
  template:
    metadata:
      labels:
        app:  project-wta
    spec:
      containers:
      - name:  project-wta-api
        image:  weslenalmeida/project-authentication:dev
        ports:
          - containerPort: 80
        env:
          - name: MongoSettings__DatabaseName
            value: "WtaManagementCars"
          - name: MongoSettings__ConnectionString
            value: "mongodb://192.168.49.2:27017"
          - name: RedisSettings__ConnectionString
            value: "project-wta-aut-redis-svc"
          - name: Authorization__ApiKey
            value: "3a20b0d9-d576-4300-b5be-f4f23664feee" 
          - name: TokenConfiguration__Key
            value: "G9VF4C6KFV43JH6GKCDFGJH45V36JHGV3H5C6F3GJC63HG45GH6V348GHHJ4623FJL3HCVMO2P23PZ07W9"
          - name: DomainsAllowed
            value: "project-wta-aut-api-svc"              
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
          limits:
            cpu: 300m
            memory: 300Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10    
        terminationMessagePath: /local/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%    
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: project-wta-api-hpa
  namespace: project-wta
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project-wta
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60


 
 

    

    
    
      